### ISSUE TITLE
Missing support for Austin 3

### ISSUE THREAD

**Issue by P403n1x87** [P403n1x87/austin-web#2]
### Description

Support for Austin 3 is currently missing. This would require similar changes to those made to the sibling project [austin-tui][tui].

[tui]: https://github.com/p403n1x87/austin-tui

**Comment by mberdyshev** [comment]
Hi! Is there any hope for this to be done?

**Comment by P403n1x87** [comment]
@mberdyshev thanks for your interest in this feature. This is currently not on my radar unfortunately, as my focus has been on other Austin tools, such as the [VS Code extension](https://marketplace.visualstudio.com/items?itemName=p403n1x87.austin-vscode). The latest version of the [TUI](https://github.com/P403n1x87/austin-tui?tab=readme-ov-file#graph-mode) offers a terminal-based version of this project. These perhaps can provide an alternative to Austin Web.

However, I'd be happy to hear about your use-case for Austin Web, in case the existing tools are not able to cover your needs. This might help me re-evaluate my current prioritisations, and give focus to features that users might find more useful 🙏 .

**Comment by P403n1x87** [comment]
@mberdyshev if you don't mind installing from a branch, could you try #7, please?

**Comment by P403n1x87** [comment]
Turned out to be relatively easy to support the latest Austin. Solved in #7.

**Comment by mberdyshev** [comment]
@P403n1x87 I'm sorry for the long delay answering your question.
I've just installed `austin-web==0.3.0` and it seems to work properly now. I can fully observe the stack frames of my program in a browser. With some bugs, but it works, at least.
Thank you for your work!

**Comment by P403n1x87** [comment]
@mberdyshev thanks for the feedback. Would you mind opening any new issues so that we can look into those bugs? 🙏

**Comment by mberdyshev** [comment]
Opened #8
